CREATE TABLE blog (blog_id INTEGER PRIMARY KEY AUTOINCREMENT, title VARCHAR(30), body TEXT, author_id INTEGER);
CREATE TABLE comment (comment_id INTEGER PRIMARY KEY AUTOINCREMENT, blog_id INTEGER, body TEXT, author_id INTEGER);
CREATE TABLE user (user_id INTEGER PRIMARY KEY AUTOINCREMENT, username VARCHAR(30), password VARCHAR(30));
CREATE TABLE profile (profile_id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER, fav_colour VARCHAR(30), age INTEGER);
