CREATE TABLE blog (blog_id INTEGER PRIMARY KEY AUTOINCREMENT, title VARCHAR(30), the_blog_user INTEGER);
CREATE TABLE comment (comment_id INTEGER PRIMARY KEY AUTOINCREMENT, title VARCHAR(30), the_comment_user INTEGER, blog_id INTEGER);
CREATE TABLE user (user_id INTEGER PRIMARY KEY AUTOINCREMENT, name VARCHAR(30));
CREATE TABLE tag (tag_id INTEGER PRIMARY KEY AUTOINCREMENT, tag VARCHAR(30));
CREATE TABLE profile (profile_id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER, age INTEGER);
CREATE TABLE blog_tag (blog_tag_id INTEGER PRIMARY KEY AUTOINCREMENT, the_blog_id INTEGER, the_tag_id INTEGER);
CREATE TABLE comment_tag (comment_tag_id INTEGER PRIMARY KEY AUTOINCREMENT, comment_id INTEGER, tag_id INTEGER);